### ISSUE TITLE
Incompatibility with supplementaries

### ISSUE THREAD

**Issue by AnomalousDeity** [Apothicon02/Apothitweaks#1]
I'm already guessing it a incompatibility based on it look like its trying to overwrite mixins but i figure to put it here in case others run into similar issues. forge 1.20.1, respectively the mods are on their latest versions, done a fresh install as well.

latest- https://mclo.gs/09zxnlP
debug-https://mclo.gs/nwdSrV3

**Comment by Apothicon02** [comment]
This is from us both mixing into the skeleton ranged attack method. You will be able to disable the mixin when I figure out a way to let people disable them. Until then you cant use both mods together.

**Comment by MehVahdJukaar** [comment]
to add onto this, issue is totally on your side because you are using overwrites. My mixin is an inject which is a compatible type of mixin that can only ever fail when somebody else uses an incompatible one (overwrite or redirect).
 You should almost never have to use overwites as for most use cases theres always a more compatible solution. Infact only real case for overwrite is if you are replacing the logic of that stuff with something completley different that is _meant_ to be incompaitble with everyhting else

**Comment by Apothicon02** [comment]
Issue is fixed with the addition of the config in the recent update. Simply disable skeleton inaccuracy in the config.
